channels:
  - conda-forge
  - nodefaults
dependencies:
  - python >=3.11
  - jupyterlab
  - cython
  - numpy >=1.14.0
  - pandas
  # - julia >=1.8.5  # we install julia via plain Project.toml which is handled by repo2docker
  - pyjulia >=0.6.0  # when installed via pip, this package is simply called "julia"
  - pip
  - pip:
    # install Cython package and Pluto server via setup.py
    - .