#!/bin/bash
# we use threads=1 because there seems to be a weird interaction with juliacall and multiple threads
export JULIA_NUM_THREADS=1
# juliacall/pythoncall
export PYTHON_JULIACALL_THREADS=1
exec "$@"